$PROJ_HOME/rtl/define.v
$PROJ_HOME/rtl/sram_model.v
$PROJ_HOME/rtl/InstMonitor.v
$PROJ_HOME/rtl/Fetch0.v
$PROJ_HOME/rtl/Icache.v
$PROJ_HOME/rtl/InstQueue.v
$PROJ_HOME/rtl/FuncDecodeEntry.v
$PROJ_HOME/rtl/Decoder.v
$PROJ_HOME/rtl/Regfile.v
$PROJ_HOME/rtl/Operands.v
$PROJ_HOME/rtl/Exe_sequencer.v
$PROJ_HOME/rtl/Adder.v
$PROJ_HOME/rtl/ALU.v
$PROJ_HOME/rtl/BEU.v
$PROJ_HOME/rtl/Scoreboard.v
$PROJ_HOME/rtl/WriteBack.v
$PROJ_HOME/rtl/LSU.v
$PROJ_HOME/rtl/BIU.v
$PROJ_HOME/rtl/Kiwi.v